export const hiddenOffers = [
    'subscriber special duke nukem forever',
    'steam key - random stuff ive given away',
    'catchem',
    'starship annihilator',
    'level up simulator',
    'the nightmare',
    'nuc after the blast',
    'farmland realm',
    'achievement killer',
    'defense of roman britain',
    'crown champion legends of the arena',
    'peppy\'s adventure',
    'particula',
    'wayout',
    'eight mini racers',
    'viki spotter the farm',
    'ostalgie the berlin wall',
    'hover hazard',
    'conflict craft',
    'cubicle quest',
    'memories of a vagabond',
    'the deed dynasty',
    'the deed',
    'gog - disjunction',
    'hidden and dangerous action pack',
    'sid meiers colonization',
    'sid meiers covert action',
    'sid meiers railroads',
    'emily is away <3',
    'army men rts',
    'paw paw paw',
    'xcom complete pack',
    'railroad tycoon 3',
    'symmetry',
    'sid meier’s ace patrol',
    'genesis noir',
    'empire of the gods',
    'starsand',
    'where the water tastes like wine',
    'blackguards deluxe edition',
    'scheming through the zombie apocalypse the beg.',
    'knights of pen and paper 2',
    'five dates',
    'the amazing american circus',
    'monster crown',
    'the serpent rogue',
    'danger scavenger',
    'stygian reign of the old ones',
    'post void',
    'darkest hour: a hearts of iron game',
    'shady part of me',
    'arcade spirits',
    'purrfect date',
    'lovecrafts untold stories',
    'sid meier\'s starships',
    'pawnbarian',
    'driftland magic revival',
    'super magbot',
    'stubbs the zombie in rebel without a pulse',
    'radio commander',
    'morbid the seven acolytes',
    'conan chop chop',
    'treasure hunter simulator',
    'surroundead',
    'fallout a post nuclear role playing game',
    'omno',
    'orcs must die 2',
    'orwell ignorance is strength',
    'tohu',
    'toem',
    'wwe 2k battlegrounds',
    'legend of keepers career of a dungeon manager',
    'john wick hex',
    'guts and glory',
    'crown trick',
    'rogue lords',
    'rustler',
    'hotshot racing',
    'guacamelee! super turbo championship edition',
    'othercide',
    'due process',
    'scourgebringer',
    'blue fire',
    'pikuniku',
    'niffelheim',
    'gauntlet slayer edition',
    'company of heroes 2',
    'call of juarez gunslinger',
    'atom rpg trudograd',
    'payday 2',
    'the last campfire',
    'outlast 2',
    'gris',
    'killing floor 2 digital deluxe edition',
    'bioshock infinite',
    'borderlands the pre-sequel',
    'destroy all humans',
    'plateup',
    'borderlands the handsome collection',
    'horizon zero dawn complete edition',
    'warsaw'
];
